name: Feature Request
description: Suggest an idea for this project
labels: [idea, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest this feature request!
  - type: textarea
    id: use_case
    attributes:
      label: 'Is your feature request related to a problem?'
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution or feature you'd like"
      description: 'A clear and concise description of what you want to happen.'
    validations:
      required: true

  - type: textarea
    id: alterntives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 'Additional context'
      description: 'Add any other context or screenshots about the feature request here.'
    validations:
      required: false
