name: Documentation issue
description: Suggestions on how we can improve the documentation
labels: [documentation]
body:
  - type: dropdown
    id: type
    attributes:
      label: What type of documentation issue are you reporting?
      multiple: true
      options:
        - Reporting a typo
        - Reporting a documentation bug
        - Documentation improvement
        - Documentation feedback
    validations:
      required: true

  - type: input
    id: docs_url
    attributes:
      label: Is there a specific documentation page you are reporting?
      value: Enter the URL here.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: 'Additional context or description'
      description: 'Add any other context or screenshots about the documentation request here.'
    validations:
      required: true
